credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrateur
      password: $2b$12$8p0Pr0Ec0ow/6fzJNVM5MOvLnyEcxY4IDamyTJZEB7Qc0ZGlYFw6O  # Remplacez par votre hash
    utilisateur:
      email: user@example.com
      name: Utilisateur Standard
      password: $2b$12$d/q/uy7EBQ06fi.CF0mqQO8ofO71xaH9fkrD.GZ88w4T4f8wgHlzW  # Remplacez par votre hash

cookie:
  expiry_days: 1
  key: votre_cle_secrete_unic0de_123!  # Changer cette valeur
  name: prayer_app_cookie
